# Generated by Django 5.1.4 on 2025-01-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('page', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='books', to='book.category')),
            ],
        ),
    ]
